#!/bin/bash

###############################################################################
# 🚀 INSTRUÇÕES FINAIS DE DEPLOY - n.Oficios
# Execute estes comandos para completar o deploy na VPS
###############################################################################

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🎯 n.Oficios - Deploy Final"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Build concluído: /home/resper/noficios-deploy.tar.gz (211KB)"
echo ""
echo "📋 PRÓXIMOS PASSOS:"
echo ""
echo "1️⃣ Copiar para VPS:"
echo "   scp /home/resper/noficios-deploy.tar.gz root@62.72.8.164:/opt/"
echo ""
echo "2️⃣ SSH na VPS e executar:"
echo ""
echo "   ssh root@62.72.8.164"
echo ""
echo "   # Backup"
echo "   cd /opt"
echo "   mv oficios oficios-backup-\$(date +%Y%m%d-%H%M%S)"
echo ""
echo "   # Descompactar"
echo "   mkdir -p oficios && cd oficios"
echo "   tar -xzf /opt/noficios-deploy.tar.gz"
echo ""
echo "   # Configurar .env"
echo "   nano .env"
echo "   # ⚠️ Cole variáveis de DEPLOY_MANUAL_VPS.md"
echo "   # ⚠️ OBTER SUPABASE_SERVICE_KEY do dashboard!"
echo ""
echo "   # Rebuild Docker"
echo "   docker-compose down"
echo "   docker system prune -f --volumes"
echo "   docker-compose build --no-cache --force-rm"
echo "   docker-compose up -d --force-recreate"
echo ""
echo "   # Verificar"
echo "   docker-compose ps"
echo "   docker-compose logs --tail=100"
echo ""
echo "3️⃣ Testar aplicação:"
echo "   https://oficio.ness.tec.br"
echo "   https://oficio.ness.tec.br/revisao/mock-1"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📚 Guias disponíveis:"
echo "   - README_DEPLOY_AGORA.md (comandos rápidos)"
echo "   - DEPLOY_MANUAL_VPS.md (passo a passo detalhado)"
echo "   - CHECKLIST_DEPLOY.md (checklist completo)"
echo "   - PROJECT_JOURNAL.md (journal do projeto)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎉 Deploy preparado! Execute os comandos acima."
echo ""

